apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: remote-sleeper-api-pipeline
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    system: remote
spec:
  project: default
  source:
    repoURL: https://github.com/contract-first-idp-qa/developer-charts
    targetRevision: HEAD
    path: api-specification-pipeline
    helm:
      values: |
        domain: contract-first-idp-qa
        system: remote
        component: sleeper
        groupid: com.redhat.demo.remote
        apicurioRegistry: registry-apicurio-registry.apps.cluster-2d8zb.2d8zb.sandbox1283.opentlc.com
        mockRegistry: microcks-microcks.apps.cluster-2d8zb.2d8zb.sandbox1283.opentlc.com
  destination:
    server: https://kubernetes.default.svc
    namespace: remote-build
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
